# Generated by Django 6.0.7 on 2026-07-19 20:19

from django.db import migrations

# Initial contact statuses required by the application
# (referenced by name during CSV import).
STATUS_NAMES = ["nowy", "w trakcie", "zagubiony", "nieaktualny"]


def create_statuses(apps, schema_editor):
    """Seed the database with default contact statuses."""
    # Use the historical model version, not a direct import from models.py
    ContactStatusChoices = apps.get_model("contacts", "ContactStatusChoices")
    for name in STATUS_NAMES:
        ContactStatusChoices.objects.get_or_create(name=name)


def remove_statuses(apps, schema_editor):
    """Reverse operation - allows unapplying this migration."""
    ContactStatusChoices = apps.get_model("contacts", "ContactStatusChoices")
    ContactStatusChoices.objects.filter(name__in=STATUS_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_statuses, remove_statuses),
    ]
